config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'groups#index'

  resources :users, only: [:edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :messages
  has_many :group_members
  has_many :users, through: :group_members
  validates :name, presence: true, uniqueness: true

  def show_latest_message
    if (last_message = messages.last).present?
      last_message.text? ? last_message.text : 'Photo'
    else
      'No Message have registered'
    end
  end
end

app/models/group_member.rb
class GroupMember < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :text, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
  has_many :group_members
  has_many :groups, through: :group_members
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
    @group = Group.find(3)
  end

  def edit
    
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'New Group created'
    else
      render :new
    end
  end

  def destroy
    
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [] )
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      redirect_to group_messages_path(@group), notice: 'メッセージが送信されました'
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:text, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
    
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count} error/s has occure"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'enter group name'
  .chat-group-form__field.clearfix
    / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} chat member
    .chat-group-form__field--right
      / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
      = f.collection_check_boxes :user_ids, User.all, :id, :nickname
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/_sideBar.html.haml
.sideHeader
  .sideHeader__box
    .sideHeader__box__userName
      = current_user.nickname
    %ul.sideHeader__box__menu
      %li
        = link_to new_group_path do
          %i.fa.fa-pencil-square-o
      %li
        = link_to edit_user_path(current_user) do
          %i.fa.fa-cog
.sideContent
  - current_user.groups.each do |group|
    .sideContent__box
      = link_to groups_path(group) do
        .sideContent__box__groupName
          = group.name
        .sideContent__box__messageBox
          no message yet

app/views/groups/edit.html.haml
.chat-group-form
  %h1 EDIT Chat Group
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
%body
  .sideBar
    = render partial: 'sideBar'
  .mainContent
    .mainHeader
      .mainHeader__rightBox
        %h2.mainHeader__rightBox__groupName
          group hoge
        %h4.mainHeader__rightBox__groupMember
          name: hogehoge, hogeee, hogege, hogee
      = link_to new_group_path do
        .mainHeader__editButton
          EDIT
    .mainMessageLender
      .mainMessageLender__upperBox
        %p.mainMessageLender__upperBox__nameBox
          jack
        %p.mainMessageLender__upperBox__timestamp
          1993/5/2 20:31
      .mainMessageLender__messageBox
        this is my message
    .mainForm
      .mainForm__box
        .mainForm__box__innerBox
          = form_for[@group, @message] do |f|
            = f.text_field :text, placeholder: 'input your message' 
            %label.mainForm__box__innerBox__message__image
              %i.upload_picture.fa.fa-picture-o.fa-lg
              %input.hidden{type: 'file'}
            = f.submit "send",{class: "mainForm__box__innerBox__button"}

app/views/groups/new.html.haml
.chat-group-form
  %h1 Create Chat Group
  = render partial: 'form', locals: { group: @group }

app/views/layouts/_flash.html.haml
.flash
  - flash.each do |key, value|
    = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/flash'
    = yield

app/views/message/inex.html.haml
!!! 5
%html
  %head
    %meta charset="utf-8"
    %title Chat Space
    - stylesheet_link_tag "application", :media => "all"
  %body
    .side-bar
      .side-header
        .side-header-box
          .side-header-box-user-name
            hogehoge
          %ul{class="side-header-box-menu"}
            %li
              %i{class="fa fa-pencil-square-o" aria-hidden="true"}
            %li
              %i{class="fa fa-cog" aria-hidden="true"}
      .side-content
        .side-content-box
          %h2{class="side-content-group-name"}
            group hoge
          %h4{class="side-content-message-box"}
            hoge message
    .main-content
      .main-header
        .main-header-right-box
          %h2{class="main-header-group-name"}
            group hoge
          %h4{class="main-header-group-member"}
          name: hogehoge, hogeee, hogege, hogee
        .main-header-edit-button
          EDIT
      .main-message-lender
        .main-message-lender-upperbox
          %p{class="upperbox-namebox"}
            jack
          %p{class="upperbox-timestamp"}
            1993/5/2 20:31
        .main-message-lender-messagebox
          this is my message
      .main-type-form
        .main-type-form-box
          .main-type-form-innerbox
            .message
              type a text
            %label{class="message-image"}
              %i{class="fa fa-picture-o fa-lg" aria-hidden="true"}
          .main-type-form-button
            SEND

app/views/messages/_message.html.haml
.mainMessageLender__upperBox
  %p.mainMessageLender__upperBox__nameBox
    = message.user.nickname
  %p.mainMessageLender__upperBox__timestamp
    = message.created_at.strftime("%Y/%m/%d %H:%M")
.mainMessageLender__messageBox
  - if message.text.present?
    = message.text
  = image_tag message.image.url if message.image.present?

app/views/messages/_sideBar.html.haml
.sideHeader
  .sideHeader__box
    .sideHeader__box__userName
      = current_user.nickname
    %ul.sideHeader__box__menu
      %li
        = link_to new_group_path do
          %i.fa.fa-pencil-square-o
      %li
        = link_to edit_user_path(current_user) do
          %i.fa.fa-cog
.sideContent
  - current_user.groups.each do |group|
    .sideContent__box
      = link_to group_messages_path(group) do
        .sideContent__box__groupName
          = group.name
        .sideContent__box__messageBox
          = group.show_latest_message

app/views/messages/index.html.haml
%body
  .sideBar
    = render partial: 'sideBar'
  .mainContent
    .mainHeader
      .mainHeader__rightBox
        %h2.mainHeader__rightBox__groupName
          = @group.name
        %h4.mainHeader__rightBox__groupMember
          = @group.users[1].nickname
      = link_to new_group_path do
        .mainHeader__editButton
          EDIT
    .mainMessageLender
      = render @messages 
    .mainForm
      .mainForm__box
        .mainForm__box__innerBox
          = form_for [@group, @message] do |f|
            = f.text_field :text, placeholder: 'input your message' 
            = f.label :image, class: 'mainForm__box__innerBox__message__image' do
              %i.upload_picture.fa.fa-picture-o.fa-lg
              = f.file_field :image, class: 'hidden'
            = f.submit "send", class: "mainForm__box__innerBox__button"



            

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 Edit Account
      = link_to "LOGOUT", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "Back to Toppage", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :nickname
          .field-input
            = f.text_field :nickname, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'